include_role 'base'

include_cookbook 'curl'
include_cookbook 'git'
include_cookbook 'ghq'
include_cookbook 'tmux'
include_cookbook 'zsh'
include_cookbook 'zplug'
include_cookbook 'asdf'
include_cookbook 'fzf'
include_cookbook 'direnv'
include_cookbook 'neovim'
include_cookbook 'powerline'
include_cookbook 'ripgrep'
include_cookbook 'delta'
include_cookbook 'bat'
include_cookbook 'gpg'
include_cookbook 'jq'
