pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "status-success=build-on-macos"
      - "status-success=build-on-ubnuntu"
      - "label=automerge"
    actions:
      merge:
        method: merge
