#!/bin/sh

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
    if [ "$local_sha" = $z40 ]
    then
        # Handle delete
        :
    else
        if [ "$remote_sha" = $z40 ]
        then
            # New branch, examine all commits
            range="$local_sha"
        else
            # Update to existing branch, examine new commits
            range="$remote_sha..$local_sha"
        fi

        # Check if commits being pushed contains now commit
        commit=`git rev-list -n 1 --grep '^\[from now\]' "$range"`
        if [ -n "$commit" ]
        then
            echo >&2 "Found now commit in $local_ref, cancel pushing"
            exit 1
        fi
    fi
done

exit 0
