name: install_and_test

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest] 
    steps:
    - uses: actions/checkout@v1
    - name: Install curl and bats with brew
      run:  brew install curl bats
    - name: Execute install.sh
      run:  ./install.sh -y
    - name: Run tests for Darwin
      run:  bats --tap tests/darwin/**.bats
