name: install_and_test

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest] 
    steps:
    - uses: actions/checkout@v1
    - name: Install HomeBrew
      run:  |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew doctor
    - name: Install curl and bats with brew
      run:  brew install curl bats
    - name: Execute init.sh
      run:  bash -c $(curl -fsSL https://raw.githubusercontent.com/Kunado/dotfiles/master/init.sh)
    - name: Run tests for Darwin
      run:  bats --tap tests/darwin/**.bats
